services:
  api:
    image: ghcr.io/jjermany/optimizarr-api:latest
    container_name: optimizarr-api
    volumes:
      - /mnt/user/data/media:/media
      - /mnt/cache/appdata/optimizarr:/config
      - /mnt/cache/appdata/optimizarr/tmp:/cache
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  frontend:
    image: ghcr.io/jjermany/optimizarr-frontend:latest
    container_name: optimizarr-frontend
    ports:
      - "8085:80"
    depends_on:
      - api
    restart: unless-stopped