services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: optimizarr-api
    volumes:
      - ./media:/media
      - ./config:/config
      - ./cache:/cache
    devices:
      - /dev/dri:/dev/dri
    environment:
      - LIBVA_DRIVER_NAME=iHD
      - QSV_DEVICE=/dev/dri/renderD128
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: optimizarr-frontend
    depends_on:
      - api
    ports:
      - "8085:80"
    restart: unless-stopped