version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: optimizarr-api
    volumes:
      - ./data/media:/media
      - ./data/config:/config
      - ./data/cache:/cache
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: optimizarr-frontend
    depends_on:
      - api
    ports:
      - "8085:80"
    restart: unless-stopped